title = "Seoyeong Park"
baseURL = "https://seoyeongpark.github.io/"
googleAnalytics = "UA-155143039-2"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Raleigh, North Carolina"
email = "seoyeong.park@alumni.stonybrook.edu"
schoolemail = "spark43@ncsu.edu"
favicon = "/rocket.ico"
firstName = "Seoyeong"
lastName = "Park"
phone = "82-10-3046-6201"
profileImage = "img/profile-seoyeong.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = true
showSkills = true
showBlog= false

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/seoyeongpark/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/seoyeongpark/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"